version: '3.8'

services:
  viewer:
    build: ./docker/viewer
    container_name: scraper-viewer
    ports:
      - "6080:6080"
    environment:
      - DISPLAY=:99
    volumes:
      - x11-socket:/tmp/.X11-unix
    shm_size: '2gb'
    ipc: shareable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: scraper-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  api:
    build: .
    container_name: scraper-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SFTP_API_URL=${SFTP_API_URL:-https://sftp-api-production.up.railway.app}
      - SFTP_API_KEY=${SFTP_API_KEY:-xs0*Zff7V6BemA3>r<[}
      - SFTP_BASE_PATH=${SFTP_BASE_PATH:-/scraping_data}
      - VIEWER_HOST=viewer
      - DISPLAY=:99
      - DATABASE_PATH=/data/scraper.db
      - API_KEY=${API_KEY:-scraping-homecare-2025-secret-key}
      - DATA_DIR=/data
      - ENVIRONMENT=development
    volumes:
      - ./data:/data
      - x11-socket:/tmp/.X11-unix
    depends_on:
      - viewer
      - redis
    ipc: "service:viewer"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  worker:
    build: .
    container_name: scraper-worker
    command: python start_worker.py
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SFTP_API_URL=${SFTP_API_URL:-https://sftp-api-production.up.railway.app}
      - SFTP_API_KEY=${SFTP_API_KEY:-xs0*Zff7V6BemA3>r<[}
      - SFTP_BASE_PATH=${SFTP_BASE_PATH:-/scraping_data}
      - DATABASE_PATH=/data/scraper.db
      - DATA_DIR=/data
    volumes:
      - ./data:/data
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  x11-socket:
  data:
    driver: local

